# This is a TOML document. Boom.

[login]
cookie="JSESSIONID=CC3004555D2D77660E48E0EB6F02FECE; BIGipServerotn=2530476298.64545.0000; _jc_save_fromStation=%u6B66%u6C49%2CWHN; _jc_save_toStation=%u91CD%u5E86%2CCQW; _jc_save_fromDate=2014-01-21; _jc_save_toDate=2014-01-02; _jc_save_wfdc_flag=dc"

user_agent="Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36"


[order_info]
#车次
train_code=[
"T250",
"T260",
"K1024"
]
#出发时间
train_date="2014-01-21"
#起点站，在查询的时候，抓包下，看看URL上面的地址
from_station="WHN"
#终点站
to_station="CQW"
#乘客姓名
passenger_name=[
  "testa",
  "testb",
  "testc",
  "testd",
  "teste"
]
#目前只支持硬卧
#硬卧3 硬座
seat_type = "3"


[system]
proxy=false
proxy_url= "http://127.0.0.1:9087"
#日志级别
log_level=2
#刷新时间毫秒
refresh_time=7100
#订单提交队列
order_size=1

#成功或者出错后打开的东西，用于提醒
#open="C:/Program Files/Internet Explorer/iexplore.exe"
open ="explorer"
open_params ="https://kyfw.12306.cn/otn/"

cdn = [
"119.36.195.228",
"220.113.9.116",
"220.113.9.114",
"219.243.47.167",
"220.113.9.115",
"123.125.92.28",
"202.204.80.76",
"219.243.47.166",
"221.130.17.40",
"162.105.28.233",
"112.25.35.62",
"221.130.17.42",
"110.18.244.166",
"124.14.10.18",
"124.254.47.194",
"122.70.142.160",
"124.14.10.24",
"221.238.252.180",
"113.229.252.37",
"202.102.254.189",
"211.162.127.77"
]


[order_request]
tour_flag="dc"
purpose_codes="ADULT"
cancel_flag="2"
bed_level_order_num="000000000000000000000000000000"

[get_queue_count]
train_date="Mon+Jan+20+2014+11%3A10%3A31+GMT%2B0800+(China+Standard+Time)"
purpose_codes="ADULT"
_json_att=""

[confirm_single_for_queue]
randCode=""
purpose_codes="ADULT"
train_location="N2"
_json_att=""

