# This is a TOML document. Boom.

[login]
cookie="JSESSIONID=1295F209F48B4A699AEF8653253E133E; _jc_save_fromStation=%u4E4C%u9C81%u6728%u9F50%2CWMR; _jc_save_toStation=%u897F%u5B89%2CXAY; _jc_save_fromDate=2014-01-21; _jc_save_toDate=2014-01-03; _jc_save_wfdc_flag=dc; BIGipServerotn=2245263626.24610.0000"

user_agent="Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36"


[order_info]
#车次
train_code=[
"T250",
"T260",
"K1024"
]
#出发时间
train_date=[
"2014-01-22"
]
#起点站
from_station="武汉"
#终点站
to_station="重庆"
#乘客姓名
passenger_name=[
  "testa",
  "testb",
  "testc",
  "testd",
  "teste"
]

# 硬座=="1" 软座=="2" 硬卧=="3" 软卧=="4" 
seat_type = "3"
seat_type_name = "硬卧"


[system]
proxy=false
proxy_url= "http://127.0.0.1:9087"
#日志级别
log_level=2
#查询间隔时间 毫秒
refresh_time=7100
#订单提交队列 默认为1,改为其他容易被踢掉
order_size=1
#订单提交前冻结时间 毫秒
submit_time=2800

#成功或者出错后打开的东西，用于提醒
#open="C:/Program Files/Internet Explorer/iexplore.exe"
open ="explorer"
open_params ="https://kyfw.12306.cn/otn/"

#mobile=""
#show_cdn=true
#query_size=10

cdn = [
"113.57.187.29",
"119.36.195.228",
"110.18.244.166",
"125.39.19.91",
"112.84.105.38",
"182.118.15.39",
"123.159.205.208",
"175.43.20.80",
"123.138.60.197",
"202.102.254.188",
"202.102.254.189",
"202.102.254.190",
"112.65.220.39",
"124.163.221.44",
"113.229.252.37",
"112.253.19.173",
"163.177.242.54",
"175.43.124.200",
"112.91.29.16",
"112.194.138.176",
"113.207.63.162",
"123.138.60.183"
]


[order_request]
tour_flag="dc"
purpose_codes="ADULT"
cancel_flag="2"
bed_level_order_num="000000000000000000000000000000"

[get_queue_count]
train_date="Mon+Jan+20+2014+11%3A10%3A31+GMT%2B0800+(China+Standard+Time)"
purpose_codes="ADULT"
_json_att=""

[confirm_single_for_queue]
randCode=""
purpose_codes="ADULT"
_json_att=""

